web:
  restart: always
  build: .
  ports:
    - "5000:5000"
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app
  links:
    - "postgres:postgres"

iddata:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - iddata
  ports:
    - "5432:5432"
